### ISSUE TITLE
Preprocessed Data Set - Access Denied?

### ISSUE THREAD

**Issue by CPerscheid** [joed3/GTExV6PRareVariation#1]
Hi all,

I just came across your nature paper and am highly interested in the data set you used for your analysis. Unfortunately, the download link you provide for the preprocessed data set tells me that access is denied. Is there another possibility to get the preprocessed data set?

Best,

Cindy

**Comment by joed3** [comment]
Hey Cindy, 

Sorry about that. The read permissions for the file weren't set correctly. I updated them to be public access, so you should be able to download it now. Please let me know if there is still a problem. Thanks for using our data!

Best,

Joe
