### ISSUE TITLE
Download of dbGap data

### ISSUE THREAD

**Issue by CPerscheid** [joed3/GTExV6PRareVariation#2]
Hi there, 
in the readme file, you suggest to download the variant data from dbGap:

> Download from dbGaP: 
>(It is possible some of the file names may be different in the final release.)
>GTEx_Analysis_2015-01-12_WholeGenomeSeq_148Indiv_GATK_HaplotypeCaller.vcf.gz
>ASE files
>GTEx_Data_V6_Annotations_SampleAttributesDS.txt
>GTEx_Analysis_2015-01-12_Annotations_SubjectPhenotypesDS.txt

Well, I currently cannot find the data files in there. If they have renamed the data files meanwhile, I would suggest you to provide the updated file name. However, I currently do not have access to the controlled data - does all this data belong to the controlled access and is thus hidden in there?

Best,

Cindy

**Comment by ektsang** [comment]
Those files are part of the controlled data because they include genotype data or other identifiable sample/subject information. You will need to apply for access to the controlled data to download those files. Unfortunately, we cannot share those particular data files in any other way.

**Comment by CPerscheid** [comment]
*sigh* all right, so I then have to decide whether to go that long way. I just wanted to make sure that all of them is located in the controlled access area and has not been renamed meanwhile. 
If you want to laugh a bit, have a look at this blog post about what it takes to apply for controlled access data from outside US: https://blog.repositive.io/watching-paint-dry-in-the-21st-century-or-applying-for-data-from-dbgap/

Best, 
Cindy
